// index.js
// Sakib branch e N ta commit banay, push kore, thomas-shelby repo te PR pathay.

require("dotenv").config();
const simpleGit = require("simple-git");
const { Octokit } = require("@octokit/rest");
const fs = require("fs");
const path = require("path");

const {
  GITHUB_TOKEN,      // hafiz-sakib er personal access token (repo scope)
  REPO_OWNER,         // thomas-shelby (repo malik)
  REPO_NAME,          // repo naam
  BRANCH_NAME = "sakib",
  COMMIT_COUNT = "5",
  LOCAL_REPO_PATH = "./repo",
  FILE_NAME = "log.txt",
} = process.env;

if (!GITHUB_TOKEN || !REPO_OWNER || !REPO_NAME) {
  console.error("Bhai .env file e GITHUB_TOKEN, REPO_OWNER, REPO_NAME dao.");
  process.exit(1);
}

const octokit = new Octokit({ auth: GITHUB_TOKEN });
const git = simpleGit(LOCAL_REPO_PATH);

async function ensureRepoCloned() {
  const remoteUrl = `https://${GITHUB_TOKEN}@github.com/${REPO_OWNER}/${REPO_NAME}.git`;
  if (!fs.existsSync(LOCAL_REPO_PATH)) {
    console.log("Repo clone hocche...");
    await simpleGit().clone(remoteUrl, LOCAL_REPO_PATH);
  } else {
    console.log("Repo already ache, pull kortesi...");
    await git.fetch();
  }
}

async function makeCommits() {
  await git.checkoutLocalBranch(BRANCH_NAME).catch(async () => {
    // branch already thakle switch koro
    await git.checkout(BRANCH_NAME);
  });

  const filePath = path.join(LOCAL_REPO_PATH, FILE_NAME);
  const count = parseInt(COMMIT_COUNT, 10);

  for (let i = 1; i <= count; i++) {
    fs.appendFileSync(filePath, `console.log("something"); // commit ${i}\n`);
    await git.add(FILE_NAME);
    await git.commit(`chore: update log entry ${i}`);
    console.log(`Commit ${i}/${count} hoye gelo.`);
  }

  console.log("Push hocche branch:", BRANCH_NAME);
  await git.push(["-u", "origin", BRANCH_NAME, "--force"]);
}

async function createPullRequest() {
  console.log("Pull request banano hocche...");
  const pr = await octokit.pulls.create({
    owner: REPO_OWNER,
    repo: REPO_NAME,
    title: `Update from branch ${BRANCH_NAME}`,
    head: BRANCH_NAME,
    base: "main",
    body: "Automated PR generated by pr-badge-bot.",
  });
  console.log("PR banano hoye gelo:", pr.data.html_url);
}

(async () => {
  try {
    await ensureRepoCloned();
    await makeCommits();
    await createPullRequest();
    console.log("Shob kaj shesh! Ekhon thomas-shelby account theke PR merge koro.");
  } catch (err) {
    console.error("Error hoise:", err.message);
  }
})();
