/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as StringsRouteImport } from './routes/strings'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as PathfindingRouteImport } from './routes/pathfinding'
import { Route as NqueensRouteImport } from './routes/nqueens'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KnightsRouteImport } from './routes/knights'
import { Route as HanoiRouteImport } from './routes/hanoi'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GametheoryRouteImport } from './routes/gametheory'
import { Route as DpRouteImport } from './routes/dp'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as CpprunnerRouteImport } from './routes/cpprunner'
import { Route as IndexRouteImport } from './routes/index'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsRoute = StringsRouteImport.update({
  id: '/strings',
  path: '/strings',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const PathfindingRoute = PathfindingRouteImport.update({
  id: '/pathfinding',
  path: '/pathfinding',
  getParentRoute: () => rootRouteImport,
} as any)
const NqueensRoute = NqueensRouteImport.update({
  id: '/nqueens',
  path: '/nqueens',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KnightsRoute = KnightsRouteImport.update({
  id: '/knights',
  path: '/knights',
  getParentRoute: () => rootRouteImport,
} as any)
const HanoiRoute = HanoiRouteImport.update({
  id: '/hanoi',
  path: '/hanoi',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GametheoryRoute = GametheoryRouteImport.update({
  id: '/gametheory',
  path: '/gametheory',
  getParentRoute: () => rootRouteImport,
} as any)
const DpRoute = DpRouteImport.update({
  id: '/dp',
  path: '/dp',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const CpprunnerRoute = CpprunnerRouteImport.update({
  id: '/cpprunner',
  path: '/cpprunner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cpprunner': typeof CpprunnerRoute
  '/developer': typeof DeveloperRoute
  '/dp': typeof DpRoute
  '/gametheory': typeof GametheoryRoute
  '/graph': typeof GraphRoute
  '/hanoi': typeof HanoiRoute
  '/knights': typeof KnightsRoute
  '/library': typeof LibraryRoute
  '/nqueens': typeof NqueensRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cpprunner': typeof CpprunnerRoute
  '/developer': typeof DeveloperRoute
  '/dp': typeof DpRoute
  '/gametheory': typeof GametheoryRoute
  '/graph': typeof GraphRoute
  '/hanoi': typeof HanoiRoute
  '/knights': typeof KnightsRoute
  '/library': typeof LibraryRoute
  '/nqueens': typeof NqueensRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cpprunner': typeof CpprunnerRoute
  '/developer': typeof DeveloperRoute
  '/dp': typeof DpRoute
  '/gametheory': typeof GametheoryRoute
  '/graph': typeof GraphRoute
  '/hanoi': typeof HanoiRoute
  '/knights': typeof KnightsRoute
  '/library': typeof LibraryRoute
  '/nqueens': typeof NqueensRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cpprunner'
    | '/developer'
    | '/dp'
    | '/gametheory'
    | '/graph'
    | '/hanoi'
    | '/knights'
    | '/library'
    | '/nqueens'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cpprunner'
    | '/developer'
    | '/dp'
    | '/gametheory'
    | '/graph'
    | '/hanoi'
    | '/knights'
    | '/library'
    | '/nqueens'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  id:
    | '__root__'
    | '/'
    | '/cpprunner'
    | '/developer'
    | '/dp'
    | '/gametheory'
    | '/graph'
    | '/hanoi'
    | '/knights'
    | '/library'
    | '/nqueens'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CpprunnerRoute: typeof CpprunnerRoute
  DeveloperRoute: typeof DeveloperRoute
  DpRoute: typeof DpRoute
  GametheoryRoute: typeof GametheoryRoute
  GraphRoute: typeof GraphRoute
  HanoiRoute: typeof HanoiRoute
  KnightsRoute: typeof KnightsRoute
  LibraryRoute: typeof LibraryRoute
  NqueensRoute: typeof NqueensRoute
  PathfindingRoute: typeof PathfindingRoute
  SearchingRoute: typeof SearchingRoute
  SortingRoute: typeof SortingRoute
  StringsRoute: typeof StringsRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings': {
      id: '/strings'
      path: '/strings'
      fullPath: '/strings'
      preLoaderRoute: typeof StringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathfinding': {
      id: '/pathfinding'
      path: '/pathfinding'
      fullPath: '/pathfinding'
      preLoaderRoute: typeof PathfindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nqueens': {
      id: '/nqueens'
      path: '/nqueens'
      fullPath: '/nqueens'
      preLoaderRoute: typeof NqueensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knights': {
      id: '/knights'
      path: '/knights'
      fullPath: '/knights'
      preLoaderRoute: typeof KnightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hanoi': {
      id: '/hanoi'
      path: '/hanoi'
      fullPath: '/hanoi'
      preLoaderRoute: typeof HanoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gametheory': {
      id: '/gametheory'
      path: '/gametheory'
      fullPath: '/gametheory'
      preLoaderRoute: typeof GametheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp': {
      id: '/dp'
      path: '/dp'
      fullPath: '/dp'
      preLoaderRoute: typeof DpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpprunner': {
      id: '/cpprunner'
      path: '/cpprunner'
      fullPath: '/cpprunner'
      preLoaderRoute: typeof CpprunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CpprunnerRoute: CpprunnerRoute,
  DeveloperRoute: DeveloperRoute,
  DpRoute: DpRoute,
  GametheoryRoute: GametheoryRoute,
  GraphRoute: GraphRoute,
  HanoiRoute: HanoiRoute,
  KnightsRoute: KnightsRoute,
  LibraryRoute: LibraryRoute,
  NqueensRoute: NqueensRoute,
  PathfindingRoute: PathfindingRoute,
  SearchingRoute: SearchingRoute,
  SortingRoute: SortingRoute,
  StringsRoute: StringsRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
